# Generated by Django 3.2.16 on 2022-11-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_blog_id_alter_comment_id_alter_feedback_id_and_more'),
        ('home', '0004_auto_20221120_1338'),
    ]

    operations = [
    ]
