# Generated by Django 4.1 on 2023-03-27 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiring_date', models.DateTimeField()),
                ('unique_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('date_generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiring_date', models.DateTimeField()),
                ('unique_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_license_number', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=50)),
                ('trailer_axle', models.CharField(blank=True, max_length=50, null=True)),
                ('triiler_type', models.CharField(blank=True, max_length=50, null=True)),
                ('triiler_length', models.CharField(blank=True, max_length=50, null=True)),
                ('trucks_plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('trailer_license_plate', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=300)),
                ('profile_image', models.ImageField(blank=True, default='/profile/profile1.jpeg', null=True, upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, max_length=250, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, default='/profile/profile1.jpeg', null=True, upload_to='profile')),
                ('is_agent', models.BooleanField(default=False)),
                ('is_driver', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('code_active', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_phone', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'seaport'), (2, 'airport'), (3, 'both')])),
                ('description', models.CharField(max_length=300)),
                ('license', models.ImageField(blank=True, null=True, upload_to='license')),
                ('profile_image', models.ImageField(blank=True, default='/profile/profile1.jpeg', null=True, upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
