# Generated by Django 3.0 on 2022-10-09 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agent_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='imex_app.AgentType'),
        ),
    ]
