# Generated by Django 3.0 on 2022-08-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttype',
            name='type_image',
            field=models.ImageField(default=1, upload_to='type_images'),
            preserve_default=False,
        ),
    ]
