# Generated by Django 3.0 on 2022-08-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0002_agenttype_type_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttype',
            name='type_image',
            field=models.ImageField(blank=True, null=True, upload_to='type_images'),
        ),
    ]
