# Generated by Django 3.0 on 2022-10-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0002_auto_20221009_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
