# Generated by Django 3.0 on 2022-11-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0003_auto_20221030_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_agent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_client',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'client'), (2, 'agent')], default=1),
        ),
    ]
