# Generated by Django 4.1 on 2023-03-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0003_alter_agent_agent_name_alter_agent_agent_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'seaport'), (2, 'airport'), (3, 'both')], default=1),
        ),
    ]
