# Generated by Django 3.0 on 2022-09-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0003_auto_20220829_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='company_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
