# Generated by Django 3.0 on 2022-10-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0004_auto_20220918_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=205, null=True),
        ),
    ]
