# Generated by Django 3.0 on 2022-11-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0004_auto_20221102_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/profile1.jpeg', null=True, upload_to='profile'),
        ),
    ]
