# Generated by Django 4.1 on 2023-03-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0004_alter_agent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
