# Generated by Django 4.1 on 2023-03-29 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imex_app', '0005_alter_transporter_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter', to=settings.AUTH_USER_MODEL),
        ),
    ]
