# Generated by Django 3.0 on 2022-11-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0005_auto_20221104_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/profile/profile1.jpeg', null=True, upload_to='profile'),
        ),
    ]
