# Generated by Django 4.1 on 2023-03-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0006_alter_transporter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='agent',
            new_name='user',
        ),
    ]
