# Generated by Django 3.0 on 2022-10-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
