# Generated by Django 4.1 on 2023-03-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0007_rename_agent_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
