# Generated by Django 3.0 on 2022-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0007_remove_comment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
