# Generated by Django 3.0 on 2022-11-11 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imex_app', '0007_auto_20221108_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_name',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ghana_card',
            field=models.CharField(default='12345678', max_length=100),
            preserve_default=False,
        ),
    ]
