# Generated by Django 3.0 on 2022-11-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0008_auto_20221111_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_name',
            field=models.CharField(default='eritten', max_length=100),
            preserve_default=False,
        ),
    ]
