# Generated by Django 4.1 on 2023-04-05 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0008_transporter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cover_image',
            field=models.ImageField(blank=True, default='/cover/header.png', null=True, upload_to='cover'),
        ),
        migrations.AddField(
            model_name='agent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'active')], default=1),
        ),
        migrations.AddField(
            model_name='agent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='cover_image',
            field=models.ImageField(blank=True, default='/cover/header.png', null=True, upload_to='cover'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transporter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
