# Generated by Django 4.1 on 2023-04-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0009_agent_cover_image_agent_created_at_agent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pending'), (2, 'active')], default=1),
        ),
    ]
