# Generated by Django 3.0 on 2022-10-07 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0010_auto_20221005_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='imex_app.Agent'),
        ),
    ]
