# Generated by Django 3.0 on 2022-10-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0011_auto_20221007_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='city',
            field=models.CharField(blank=True, default='Accra', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='region',
            field=models.CharField(blank=True, default='Greater Accra', max_length=200, null=True),
        ),
    ]
