# Generated by Django 4.1 on 2023-04-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0011_transporterreview_agentreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporter',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='transporter',
            name='vehicle_1',
            field=models.ImageField(blank=True, default='/cover/header.png', null=True, upload_to='vehicles'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='vehicle_2',
            field=models.ImageField(blank=True, default='/cover/header.png', null=True, upload_to='vehicles'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='vehicle_3',
            field=models.ImageField(blank=True, default='/cover/header.png', null=True, upload_to='vehicles'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='vehicle_4',
            field=models.ImageField(blank=True, default='/cover/header.png', null=True, upload_to='vehicles'),
        ),
    ]
