# Generated by Django 3.2.16 on 2022-11-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imex_app', '0016_alter_agenttype_id_alter_order_id_alter_profile_id_and_more'),
        ('imex_app', '0016_auto_20221120_1338'),
    ]

    operations = [
    ]
